<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProductsImg</name>
   <tag></tag>
   <elementGuidId>3f46535e-f0c1-4966-a80d-de9e140ab90c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.inventory_details_img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='inventory_item_container']/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7c10e259-259c-4a5e-859e-97e04bd493d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sauce Labs Bike Light</value>
      <webElementGuid>19ab273a-c817-4ead-b18b-d360c0a1cebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inventory_details_img</value>
      <webElementGuid>787f412e-d4b1-4180-b074-43c1fb10632e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/bike-light-1200x1500.37c843b0.jpg</value>
      <webElementGuid>026c72b8-310b-4305-a301-991e0a11c570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>item-sauce-labs-bike-light-img</value>
      <webElementGuid>e3bf047a-ad4e-4eea-9cc8-483aeaf4d3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inventory_item_container&quot;)/div[@class=&quot;inventory_details&quot;]/div[@class=&quot;inventory_details_container&quot;]/div[@class=&quot;inventory_details_img_container&quot;]/img[@class=&quot;inventory_details_img&quot;]</value>
      <webElementGuid>38cc2458-9c7e-4024-a1a0-4eb2dcbb82ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inventory_item_container']/div/div/div/img</value>
      <webElementGuid>4c7ae01f-3802-4a37-9815-5e30ab3a3fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sauce Labs Bike Light']</value>
      <webElementGuid>b30a61f4-f41b-40e2-a571-48c971ab12f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
      <webElementGuid>2e9590f4-8799-4b34-804a-3872f87c36d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Sauce Labs Bike Light' and @src = '/static/media/bike-light-1200x1500.37c843b0.jpg']</value>
      <webElementGuid>aa161ae8-3e49-422d-8f8d-a70ca0b4dc86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
